env: 
    CONFIG: config.sh
    CIRRUS_SHELL: bash

task:
  timeout_in: 30m 
  name: "CI Docker Test"
  container:
      image: ghcr.io/ozipoetra/docker:main
      cpu: 2
      memory: 4
  test_script:
      - repo
      - echo "Repo Test Finished"
  apt_script:
      - sudo apt update
      - echo "Apt Test Finished"
